[package]
name = "vl53l5"
version = "0.1.0"
edition = "2021"

[dependencies]
c2rust-bitfields = { version = "0.19.0", features = ["no_std"] }

[dev-dependencies]
esp-hal = { version = "0.23.1", features = [
    "esp32c3",
    #"unstable",
] }

esp-println = { version = "0.13.0", features = ["esp32c3", "log"] }
esp-backtrace = { version = "0.15.0", features = [
    "esp32c3",
    "exception-handler",
    "panic-handler",
    "println",
] }
critical-section = "1.1.3"

[profile.release]
debug = 2

[patch.crates-io]
esp-hal         = { git = "https://github.com/esp-rs/esp-hal.git" }
