[target.'cfg(all())']
runner = "espflash flash --monitor"

# Note: CANNOT use 'feature' to change the runners. This does pass IDE, and builds, but works wrong.
#     It's a known thing in Rust. If you are friendly, please ask an error to be created with this kind of constructs.
#
#     At running:
#     <<
#       /home/ubuntu/target/riscv32imXc-unknown-none-elf/release/examples/basic: 1: Syntax error: "(" unexpected
#     <<
#[target.'cfg(feature="espflash-defmt")']
#runner = "espflash flash --log-format defmt --monitor"
#
#[target.'cfg(feature="probe_rs-defmt")']
#runner = ["probe-rs", "run", "--log-format={{t:dimmed} [{L:bold}]} {s}  {{c} {ff}:{l:1}%dimmed}"]

[env]
ESP_LOG="info"    # *should* affect the 'espflash-log' feature (didn't..)
DEFMT_LOG="info"  # should affect the '-defmt' features

[build]
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C", "force-frame-pointers",
]

target = "riscv32imac-unknown-none-elf"

# Unfortunately, cannot have '[build.'cfg(...)']'
#[build.'cfg(feature="_defmt")']
#rustflags = [
#  "-C", "link-arg=-Tdefmt.x"   # using 'build.rs', instead
#]
